#using GAE STD env
env: standard
runtime: python39

instance_class: F2

automatic_scaling:
  max_instances: 1
  min_instances: 1

inbound_services:
- warmup

entrypoint: gunicorn  --workers 1 --threads 16 -b :$PORT app:app


